### ISSUE TITLE
when support for 1.7

### ISSUE THREAD

**Issue by Mayeul-T** [meetjey/imageRegeneratorPrestashop#13]
Is there project to have a new version for prestashop 1.7 ?

**Comment by meetjey** [comment]
Yep ! Under 2 month it could be possible :)

**Comment by cocob35** [comment]
Hello,
do you have a prestashop 1.7 of your module ?
Best Regards,
Johann

**Comment by hh-com** [comment]
I simply changed $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '1.6'); to $this->ps_versions_compliancy = array('min' => '1.5', 'max' => '1.7'); and it seems to work fine.

**Comment by meetjey** [comment]
Request merged, thanks for help ;)
