### ISSUE TITLE
How it works 

### ISSUE THREAD

**Issue by dtwfung** [meetjey/imageRegeneratorPrestashop#4]
![screen shot](https://cloud.githubusercontent.com/assets/11907298/7104326/9955b8c2-e10a-11e4-95bd-3771278ea50d.jpg)
Hi there,
I have installed in on 1.6.0.14 but it just showed Pause, Resume and Reset. 
No action when I clicked Pause or Resume...
What might be the problem...

Many thanks

**Comment by meetjey** [comment]
Yes, there are missing things :)

You should see this : (prestashop 1.6.0.14)
![image](https://cloud.githubusercontent.com/assets/5818584/7106641/a6053c1c-e148-11e4-869f-e8b1ae3e7d34.png)

Could you open dev panel and look at console output ?

Thank you

**Comment by dtwfung** [comment]
Thanks for Your response.
What is dev panel and look at console output  ?
Should I turn on Ajax mode ?

On Mon, Apr 13, 2015 at 1:19 AM, meetjey <notifications@github.com> wrote:

> Yes, there are missing things :)
>
> You should see this : (prestashop 1.6.0.14)
> [image: image]
> <https://cloud.githubusercontent.com/assets/5818584/7106641/a6053c1c-e148-11e4-869f-e8b1ae3e7d34.png>
>
> Could you open dev panel and look at console output ?
>
> Thank you
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meetjey/imageRegeneratorPrestashop/issues/4#issuecomment-92089266>
> .
>



-- 
--------------------------------------------------------

Cheers
David Fung
+ email: dtwfung@gmail.com

"This e-mail is confidential and may also be privileged. If you are not
the intended recipient, please notify us immediately; you should not
copy or use it for any purpose, nor disclose its contents to any other
person."

--------------------------------------------------------

**Comment by nicolasdanelon** [comment]
please mark this issue as solved.

btw- nice plugin @meetjey ! This is really usefull :D
