### ISSUE TITLE
Seems not to work

### ISSUE THREAD

**Issue by rubenCodeforges** [meetjey/imageRegeneratorPrestashop#5]
Im not sure what should happen when clicking on resume , but there is no event fired.
No ajax request nothing.

Am i using it wrong ?

**Comment by rubenCodeforges** [comment]
In your js file i see you have `image_regenerator-lauch` but this button is never been created , in your php file it is also not there .
Is that module finished ?

**Comment by rubenCodeforges** [comment]
the method `query_regenerate_img()` seems not to be available to global scope

**Comment by hgus** [comment]
Hi,
I confirm it's not working.
As rubenCodeforges  said, no event firing after clicking 'resume'.

Any correction ?

**Comment by hgus** [comment]
And what about the documentation says : 
- Regenerate by type (category, product...)

??? there is no choice about it !

**Comment by hgus** [comment]
I found the problem : the js file is not linked properly for prestashop 1.6.1.4.
Line 36 of imageregenerator.php, the addJS is not working inside hookActionAdminControllerSetMedia function.
Solved by copy and paste into displayForm function line 66 : 
`public function displayForm(){
		
		if((Tools::getValue('controller') == 'AdminModules') && (Tools::getValue('configure') == $this->name))
			$this->context->controller->addJS(($this->_path).'js/ir-main.js');`

**Comment by rubenCodeforges** [comment]
@hgus  body looks like the repo is dead i did a post on July 2015 and no response :)

**Comment by hgus** [comment]
@rubenCodeforges yes it seems but with my fix it's working !

**Comment by meetjey** [comment]
Sorry for the delay ! 
I try your fix and i add it ;)

**Comment by hgus** [comment]
Yep ;)
It for presta 1.6.1.4, others versions I don't know.
