### ISSUE TITLE
Regenerate stoped and not resume

### ISSUE THREAD

**Issue by xSquallit** [meetjey/imageRegeneratorPrestashop#7]
Hi, there's a problem. I run regeneration products images. But it stops before reaching end (4831/11623). Pause/Resume does not help.
If I reenter to the module settings, the progress will be reset. Is there any way to start the regeneration of a particular product, rather than first?

Presta 1.6.1.11

**Comment by xSquallit** [comment]
Something that has helped.

Column `value` in `ps_configuration` table in Presta DB has type 'TEXT'. I changed the type to 'mediumtext', and value of `image_regenerator_queue`, which is written in the column, fully fit. Now, when you exit the module settings, progress is saved.

**Comment by centoasa** [comment]
for me instead every time I press pauses, save the queue, I do other things in prestashop (how to see the orders) return on image-regenerator, I press resume and the product counter always restarts from 1
